"""sync agenda_event model

Revision ID: 1ab1d06345a3
Revises: b2863e6e77ad
Create Date: 2026-09-17 21:25:02.428469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ab1d06345a3'
down_revision: Union[str, None] = 'b2863e6e77ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raster',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nom', sa.String(length=255), nullable=True),
        sa.Column('b2_key', sa.String(length=500), nullable=False),
        sa.Column('b2_url', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raster_id'), 'raster', ['id'], unique=False)

    op.create_table('spatial_reference',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('auth_name', sa.String(length=256), nullable=True),
        sa.Column('auth_srid', sa.Integer(), nullable=True),
        sa.Column('srtext', sa.Text(), nullable=True),
        sa.Column('proj4text', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spatial_reference_id'), 'spatial_reference', ['id'], unique=False)

    # ⚠️ SUPPRIMÉ : op.drop_table('spatial_ref_sys')  ← table système PostGIS

    # --- Insertion des SRID de base (depuis PostGIS si dispo) ---
    op.execute("""
        INSERT INTO spatial_reference (id, auth_name, auth_srid, srtext, proj4text)
        SELECT srid, auth_name, auth_srid, srtext, proj4text
        FROM spatial_ref_sys
        WHERE srid IN (4326, 3857, 2154)
    """)
    # Fallback si PostGIS n'a pas ces SRID (au cas où)
    op.execute("""
        INSERT INTO spatial_reference (id, auth_name, auth_srid, srtext, proj4text)
        VALUES (4326, 'EPSG', 4326, 'WGS 84', '+proj=longlat +datum=WGS84 +no_defs')
        ON CONFLICT (id) DO NOTHING
    """)

    # --- Modifications agenda_event ---
    op.add_column('agenda_event', sa.Column('parcel_id', sa.Integer(), nullable=True))
    op.add_column('agenda_event', sa.Column('start_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('agenda_event', sa.Column('end_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agenda_event', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.add_column('agenda_event', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('agenda_event', sa.Column('reminder_custom_unit', sa.String(length=20), nullable=True))
    op.add_column('agenda_event', sa.Column('reminder_custom_value', sa.Integer(), nullable=True))
    op.add_column('agenda_event', sa.Column('reminder_unit', sa.String(length=20), nullable=True))

    op.alter_column('agenda_event', 'title',
        existing_type=sa.VARCHAR(length=150),
        type_=sa.String(length=255),
        existing_nullable=False)
    op.alter_column('agenda_event', 'description',
        existing_type=sa.TEXT(),
        type_=sa.String(length=1000),
        existing_nullable=True)

    op.create_index(op.f('ix_agenda_event_parcel_id'), 'agenda_event', ['parcel_id'], unique=False)

    op.drop_constraint('agenda_event_user_id_fkey', 'agenda_event', type_='foreignkey')
    op.create_foreign_key(None, 'agenda_event', 'parcel', ['parcel_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agenda_event', 'utilisateur', ['user_id'], ['id'], ondelete='CASCADE')

    op.drop_column('agenda_event', 'status')
    op.drop_column('agenda_event', 'start_datetime')
    op.drop_column('agenda_event', 'end_datetime')
    op.drop_column('agenda_event', 'reminder_custom_minutes')
    op.drop_column('agenda_event', 'reminder')

    # --- Modifications parcel ---
    op.add_column('parcel', sa.Column('raster_id', sa.Integer(), nullable=True))
    op.add_column('parcel', sa.Column('spatial_reference_id', sa.Integer(), server_default='4326', nullable=False))
    op.create_index(op.f('ix_parcel_raster_id'), 'parcel', ['raster_id'], unique=False)
    op.create_index(op.f('ix_parcel_spatial_reference_id'), 'parcel', ['spatial_reference_id'], unique=False)
    op.create_foreign_key(None, 'parcel', 'raster', ['raster_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parcel', 'spatial_reference', ['spatial_reference_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parcel', type_='foreignkey')
    op.drop_constraint(None, 'parcel', type_='foreignkey')
    op.drop_index(op.f('ix_parcel_spatial_reference_id'), table_name='parcel')
    op.drop_index(op.f('ix_parcel_raster_id'), table_name='parcel')
    op.drop_column('parcel', 'spatial_reference_id')
    op.drop_column('parcel', 'raster_id')

    op.add_column('agenda_event', sa.Column('reminder', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('agenda_event', sa.Column('reminder_custom_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agenda_event', sa.Column('end_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('agenda_event', sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('agenda_event', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'a_faire'::character varying"), autoincrement=False, nullable=False))

    op.drop_constraint(None, 'agenda_event', type_='foreignkey')
    op.drop_constraint(None, 'agenda_event', type_='foreignkey')
    op.create_foreign_key('agenda_event_user_id_fkey', 'agenda_event', 'utilisateur', ['user_id'], ['id'])

    op.drop_index(op.f('ix_agenda_event_parcel_id'), table_name='agenda_event')

    op.alter_column('agenda_event', 'description',
        existing_type=sa.String(length=1000),
        type_=sa.TEXT(),
        existing_nullable=True)
    op.alter_column('agenda_event', 'title',
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=150),
        existing_nullable=False)

    op.drop_column('agenda_event', 'reminder_unit')
    op.drop_column('agenda_event', 'reminder_custom_value')
    op.drop_column('agenda_event', 'reminder_custom_unit')
    op.drop_column('agenda_event', 'reminder_sent')
    op.drop_column('agenda_event', 'event_type')
    op.drop_column('agenda_event', 'end_at')
    op.drop_column('agenda_event', 'start_at')
    op.drop_column('agenda_event', 'parcel_id')

    # ⚠️ SUPPRIMÉ : op.create_table('spatial_ref_sys', ...)  ← on ne recrée JAMAIS cette table

    op.drop_index(op.f('ix_spatial_reference_id'), table_name='spatial_reference')
    op.drop_table('spatial_reference')
    op.drop_index(op.f('ix_raster_id'), table_name='raster')
    op.drop_table('raster')
    # ### end Alembic commands ###