"""update utilisateur

Revision ID: 46b60233c8c3
Revises: 
Create Date: 2026-09-04 11:01:16.454895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b60233c8c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('utilisateur', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.drop_index('ix_utilisateur_nom_utilisateur', table_name='utilisateur')
    op.create_index(op.f('ix_utilisateur_google_id'), 'utilisateur', ['google_id'], unique=True)
    op.create_index(op.f('ix_utilisateur_username'), 'utilisateur', ['username'], unique=True)
    op.drop_column('utilisateur', 'nom_utilisateur')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('nom_utilisateur', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_utilisateur_username'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_google_id'), table_name='utilisateur')
    op.create_index('ix_utilisateur_nom_utilisateur', 'utilisateur', ['nom_utilisateur'], unique=True)
    op.drop_column('utilisateur', 'google_id')
    op.drop_column('utilisateur', 'username')
    # ### end Alembic commands ###
