"""modifier tables parcel et raster2

Revision ID: 4d6ad2b166e6
Revises: e311a8591861
Create Date: 2026-09-26 11:29:38.079658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6ad2b166e6'
down_revision: Union[str, None] = 'e311a8591861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel', sa.Column('raster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parcel_raster_id'), 'parcel', ['raster_id'], unique=False)
    op.create_foreign_key(None, 'parcel', 'raster', ['raster_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_raster_parcel_id', table_name='raster')
    op.drop_constraint('fk_raster_parcel_id', 'raster', type_='foreignkey')
    op.drop_column('raster', 'parcel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raster', sa.Column('parcel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_raster_parcel_id', 'raster', 'parcel', ['parcel_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_raster_parcel_id', 'raster', ['parcel_id'], unique=False)
    op.drop_constraint(None, 'parcel', type_='foreignkey')
    op.drop_index(op.f('ix_parcel_raster_id'), table_name='parcel')
    op.drop_column('parcel', 'raster_id')
    # ### end Alembic commands ###
