"""ajout role et password_changed_at

Revision ID: 716602d84a0a
Revises: 9014af13bfe5
Create Date: 2026-09-07 11:38:06.363488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716602d84a0a'
down_revision: Union[str, None] = '9014af13bfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('utilisateur', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'password_changed_at')
    op.drop_column('utilisateur', 'role')
    # ### end Alembic commands ###
