"""ajout status agenda_event

Revision ID: 798fa1b7e00f
Revises: 2467ccac7a25
Create Date: 2026-09-18 09:33:49.294485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798fa1b7e00f'
down_revision: Union[str, None] = '2467ccac7a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
