"""create agenda_event table

Revision ID: 9562a61acb6b
Revises: 716602d84a0a
Create Date: 2026-09-10 15:59:17.057402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9562a61acb6b'
down_revision: Union[str, None] = '716602d84a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='a_faire', nullable=False),
    sa.Column('reminder', sa.String(length=20), nullable=True),
    sa.Column('reminder_custom_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_event_id'), 'agenda_event', ['id'], unique=False)
    op.create_index(op.f('ix_agenda_event_user_id'), 'agenda_event', ['user_id'], unique=False)
    op.alter_column('utilisateur', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateur', 'avatar_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_agenda_event_user_id'), table_name='agenda_event')
    op.drop_index(op.f('ix_agenda_event_id'), table_name='agenda_event')
    op.drop_table('agenda_event')
    # ### end Alembic commands ###
