"""update raster

Revision ID: a511bacb8af0
Revises: 798fa1b7e00f
Create Date: 2026-09-22 10:31:37.893279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a511bacb8af0'
down_revision: Union[str, None] = '798fa1b7e00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raster', sa.Column('bbox_west', sa.Float(), nullable=True))
    op.add_column('raster', sa.Column('bbox_south', sa.Float(), nullable=True))
    op.add_column('raster', sa.Column('bbox_east', sa.Float(), nullable=True))
    op.add_column('raster', sa.Column('bbox_north', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raster', 'bbox_north')
    op.drop_column('raster', 'bbox_east')
    op.drop_column('raster', 'bbox_south')
    op.drop_column('raster', 'bbox_west')
    # ### end Alembic commands ###
