"""correction des tables1

Revision ID: bb0f824f40ed
Revises: 4d6ad2b166e6
Create Date: 2026-09-26 13:56:20.706463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0f824f40ed'
down_revision: Union[str, None] = '4d6ad2b166e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('hired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.String(length=10), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'employee_id', name='uq_farm_employee')
    )
    op.create_index(op.f('ix_farm_employee_employee_id'), 'farm_employee', ['employee_id'], unique=False)
    op.create_index(op.f('ix_farm_employee_farm_id'), 'farm_employee', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_employee_id'), 'farm_employee', ['id'], unique=False)
    op.add_column('raster', sa.Column('raster_type', sa.String(length=50), nullable=True))
    op.drop_index('ix_raster_type', table_name='raster')
    op.create_index(op.f('ix_raster_raster_type'), 'raster', ['raster_type'], unique=False)
    op.drop_column('raster', 'type')
    op.drop_column('raster', 'source')
    op.drop_column('raster', 'scene_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raster', sa.Column('scene_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('raster', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('raster', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_raster_raster_type'), table_name='raster')
    op.create_index('ix_raster_type', 'raster', ['type'], unique=False)
    op.drop_column('raster', 'raster_type')
    op.drop_index(op.f('ix_farm_employee_id'), table_name='farm_employee')
    op.drop_index(op.f('ix_farm_employee_farm_id'), table_name='farm_employee')
    op.drop_index(op.f('ix_farm_employee_employee_id'), table_name='farm_employee')
    op.drop_table('farm_employee')
    # ### end Alembic commands ###
