"""mettre a jour la base de données

Revision ID: d3d55754f85f
Revises: bb0f824f40ed
Create Date: 2026-09-26 14:45:52.975946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d55754f85f'
down_revision: Union[str, None] = 'bb0f824f40ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alert_parcel_id_fkey', 'alert', type_='foreignkey')
    op.create_foreign_key(None, 'alert', 'parcel', ['parcel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('indice_reading_parcel_id_fkey', 'indice_reading', type_='foreignkey')
    op.create_foreign_key(None, 'indice_reading', 'parcel', ['parcel_id'], ['id'], ondelete='CASCADE')
    op.add_column('parcel', sa.Column('raster_status', sa.String(length=20), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcel', 'raster_status')
    op.drop_constraint(None, 'indice_reading', type_='foreignkey')
    op.create_foreign_key('indice_reading_parcel_id_fkey', 'indice_reading', 'parcel', ['parcel_id'], ['id'])
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.create_foreign_key('alert_parcel_id_fkey', 'alert', 'parcel', ['parcel_id'], ['id'])
    # ### end Alembic commands ###
